Repository LOUD-Community-Edition/LOUD-Community-Edition, pull requests merged in 2024-09, with the labels that each got.

#55 Add Optional Submod (Loud Community Edition - Economy & Flow) to LCE
  hook/lua/system/Blueprints.lua
  mod_info.lua
  modules/LCE Economy & Flow/hook/lua/system/Blueprints.lua
  modules/LCE Economy & Flow/mod_info.lua
Labels: enhancement

#122 Rommel t2
  hook/lua/system/Blueprints.lua
  units/WyvernBattlePack/wel0304/WEL0304_Albedo.dds
  units/WyvernBattlePack/wel0304/WEL0304_NormalsTS.DDS
  units/WyvernBattlePack/wel0304/WEL0304_Script.lua
  units/WyvernBattlePack/wel0304/WEL0304_SpecTeam.dds
  units/WyvernBattlePack/wel0304/WEL0304_lod0.scm
  units/WyvernBattlePack/wel0304/WEL0304_lod1.scm
  units/WyvernBattlePack/wel0304/WEL0304_unit.bp
Labels: balance

#137 Removed slink stealth / disable cloak when firing behaviour
  units/BrewLAN/SRL0320/SRL0320_Script.lua
  units/BrewLAN/SRL0320/SRL0320_albedo.dds
  units/BrewLAN/SRL0320/SRL0320_lod0.scm
  units/BrewLAN/SRL0320/SRL0320_lod1.scm
  units/BrewLAN/SRL0320/SRL0320_lod1_albedo.dds
  units/BrewLAN/SRL0320/SRL0320_lod1_normalsTS.dds
  units/BrewLAN/SRL0320/SRL0320_lod1_specteam.dds
  units/BrewLAN/SRL0320/SRL0320_normalsTS.dds
  units/BrewLAN/SRL0320/SRL0320_specteam.dds
  units/BrewLAN/SRL0320/SRL0320_unit.bp
Labels: balance

#144 Initial ACU Overcharge Rework
  hook/lua/sim/DefaultProjectiles.lua
  hook/lua/sim/Unit.lua
  hook/lua/utilities.lua
  lua/shared/overcharge.lua
  lua/sim/OverchargeProjectile.lua
  projectiles/ADFOverCharge01/ADFOverCharge01_proj.bp
  projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
  projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_proj.bp
  projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
  projectiles/SDFChronatronCannon02/SDFChronatronCannon02_proj.bp
  projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
  projectiles/TDFOverCharge01/TDFOverCharge01_proj.bp
  projectiles/TDFOverCharge01/TDFOverCharge01_script.lua
  units/BlackOpsACUs/EAL0001/EAL0001_unit.bp
  units/BlackOpsACUs/EEL0001/EEL0001_unit.bp
  units/BlackOpsACUs/ERL0001/ERL0001_unit.bp
  units/BlackOpsACUs/ESL0001/ESL0001_unit.bp
Labels: enhancement, help wanted, balance

#143 Uef t3 - Helltank & Jugger
  units/BlackOpsUnleashed/BEL0307/BEL0307_unit.bp
  units/BlackOpsUnleashed/XEL0307/XEL0307_unit.bp
Labels: balance

#146 Initial Shield Overspill Rework
  hook/lua/shield.lua
  hook/lua/sim/Entity.lua
  hook/lua/sim/Projectile.lua
  hook/lua/system/utils.lua
  lua/ShieldAbsorptionValues.lua
Labels: enhancement, help wanted, balance
